# Generated by Django 5.2.9 on 2025-12-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_productdetails_product_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="brand",
            name="brand_name",
        ),
       migrations.AddField(
        model_name="brand",
        name="name",
        field=models.CharField(default="Unknown", max_length=100),
        preserve_default=False,
)

    ]
