# Generated by Django 5.2.9 on 2025-12-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_remove_brand_brand_name_brand_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(
                default="Unknown Brand", max_length=100
            ),
        ),
    ]
