# Generated by Django 5.2.9 on 2025-12-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_brand_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
