# Generated by Django 5.2.9 on 2025-12-15 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_brand_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products/"),
        ),
    ]
