# Generated by Django 5.2.9 on 2025-12-28 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetails',
            name='Discount_Price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='blog.brand'),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_link',
            field=models.URLField(default=0, max_length=500),
        ),
    ]
