# Generated by Django 5.2.9 on 2025-12-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_productdetails_discount_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='rating',
        ),
        migrations.AddField(
            model_name='productdetails',
            name='Saving',
            field=models.FloatField(default=0),
        ),
    ]
