# Generated by Django 5.2.9 on 2025-12-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_remove_productdetails_rating_productdetails_saving'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.URLField(blank=True, max_length=1000, null=True)),
                ('regular_price', models.IntegerField(default=0)),
                ('discount_price', models.IntegerField(default=0)),
                ('discount_percentage', models.CharField(blank=True, max_length=10, null=True)),
                ('link', models.URLField(max_length=1000, unique=True)),
                ('store_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
