# Generated by Django 5.2.9 on 2026-01-08 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_productlisting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopoutlet',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='shopoutlet',
            name='opening_time',
        ),
        migrations.AddField(
            model_name='shopoutlet',
            name='off_day',
            field=models.CharField(blank=True, choices=[('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='shopoutlet',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
