# Generated by Django 5.2.9 on 2026-01-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_wishlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='shop_logo',
            field=models.URLField(blank=True, help_text='Shop logo URL', max_length=500),
        ),
        migrations.AddField(
            model_name='shopoutlet',
            name='closing_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shopoutlet',
            name='opening_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
