# Generated by Django 5.2.9 on 2025-12-07 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="product_link",
            field=models.URLField(default=None, max_length=500),
        ),
    ]
