# Generated by Django 5.2.9 on 2025-12-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_productdetails_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetails",
            name="brand",
        ),
        migrations.DeleteModel(
            name="Brand",
        ),
    ]
