# Generated by Django 5.2.9 on 2025-12-17 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetails",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="brand",
                to="blog.brand",
            ),
        ),
    ]
